version: "3.2"
services:
  web:
    image: reemaah/reservation-apis:1.0.0
    restart: always
    command: ["./docker-entrypoint.sh"]
    ports:
      - "8000:8000"
    environment:
      - "DB_HOST=db"
      - "DB_PORT=5432"
      - "DB_NAME=reservation_db"
      - "DB_USERNAME=admin_user"
      - "DB_PASSWORD=passw0rd"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"

  db:
    image: postgres:9.6.12
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_reservations:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=reservation_db
  
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_reservations:/data

volumes:
  postgres_reservations:
  redis_reservations: