# Generated by Django 3.2 on 2022-04-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
